#!/bin/sh
#
# ec2-killall-nash-hotplug - Kill nash-hotplug
#
# Fedora 6/8 initrd starts nash-hotplug which, when used on an Ubuntu
# or Debian AMI, uses 100% CPU and prevents udev from starting, not to
# mention taking general performance to a crawl.
#
#

/usr/bin/killall nash-hotplug
