#!/bin/bash
#
# install-lamp-server
#

set -e
set -x

# Skip prompt for the MySQL root password
export DEBIAN_FRONTEND=noninteractive

# Upgrade
apt-get update && apt-get update -y

# Install packages.
tasksel install lamp-server

echo "Please remember to set the MySQL root password!"
